"""Writes hooks/common.ts: the English words common enough that a reader
already knows them, from wordfreq (https://github.com/rspeer/wordfreq).

    python3 -m venv /tmp/wf && /tmp/wf/bin/pip install wordfreq
    /tmp/wf/bin/python scripts/common-words.py > hooks/common.ts

THRESHOLD was chosen against a real glossary: at 3.3 "validate" (3.40),
"tests" and "pass" are common, while "diffs" (3.20), "shim", "viewport" and
"mutex" are not.
"""
import re

from wordfreq import iter_wordlist, zipf_frequency

THRESHOLD = 3.3
# Tool names and acronyms people write in lower case, whose counts the
# corpus inflates; never common.
NEVER_COMMON = {
    'api', 'cli', 'css', 'dns', 'git', 'gui', 'html', 'http', 'https', 'ide',
    'json', 'sql', 'ssh', 'url', 'usb', 'xml',
}

words = [
    w
    for w in iter_wordlist('en', 'best')
    if re.fullmatch(r'[a-z]{2,}', w)
    and w not in NEVER_COMMON
    and zipf_frequency(w, 'en') >= THRESHOLD
]
words.sort()

print('// Generated by scripts/common-words.py; do not edit by hand.')
print(f'// English words at Zipf frequency {THRESHOLD} or above ({len(words)} words).')
print('// Word data: wordfreq by Robyn Speer, https://github.com/rspeer/wordfreq,')
print('// licensed CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/).')
print('// This file alone carries that license; the rest of the plugin is MIT.')
print()
print('export const COMMON_WORDS =')
print(f"  '{' '.join(words)}'")
